### ISSUE TITLE
修改 package.json 信息时的优化

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/pim#9]
1. github 仓库的格式是形如 `owner/repo` 的形式，owner 是用户或者组织，repo 是仓库名
2. 新建仓库时，有些特殊字符是不允许的，会被转化，需要增加输入校验
3. 仓库也可以托管在 gitlab 、gitee 、gerrit 等平台，可以增加一个选择的选项
4. 有的模板可能不止预设的几个涉及地址的字段，是否考虑改用其他方式，比如正则来匹配修改
5. LICENSE 同 4 ... 每个 LICENSE 可能不一样

以上愚见，可以酌情考虑修改

**Comment by alexzhang1030** [comment]
好建议

**Comment by alexzhang1030** [comment]
> 1. github 仓库的格式是形如 `owner/repo` 的形式，owner 是用户或者组织，repo 是仓库名
> 2. 新建仓库时，有些特殊字符是不允许的，会被转化，需要增加输入校验
> 3. 仓库也可以托管在 gitlab 、gitee 、gerrit 等平台，可以增加一个选择的选项
> 4. 有的模板可能不止预设的几个涉及地址的字段，是否考虑改用其他方式，比如正则来匹配修改
> 5. LICENSE 同 4 ... 每个 LICENSE 可能不一样
> 
> 以上愚见，可以酌情考虑修改

第一点不是很明白

**Comment by LoTwT** [comment]
> > 1. github 仓库的格式是形如 `owner/repo` 的形式，owner 是用户或者组织，repo 是仓库名
> > 2. 新建仓库时，有些特殊字符是不允许的，会被转化，需要增加输入校验
> > 3. 仓库也可以托管在 gitlab 、gitee 、gerrit 等平台，可以增加一个选择的选项
> > 4. 有的模板可能不止预设的几个涉及地址的字段，是否考虑改用其他方式，比如正则来匹配修改
> > 5. LICENSE 同 4 ... 每个 LICENSE 可能不一样
> > 
> > 以上愚见，可以酌情考虑修改
> 
> 第一点不是很明白

可以参考 Github REST API [get a repository](https://docs.github.com/en/rest/repos/repos#get-a-repository) ，一个仓库可以属于个人也可以属于组织，就是对应关系上，写成 owner 会更准确...

**Comment by LoTwT** [comment]
> > > 1. github 仓库的格式是形如 `owner/repo` 的形式，owner 是用户或者组织，repo 是仓库名
> > > 2. 新建仓库时，有些特殊字符是不允许的，会被转化，需要增加输入校验
> > > 3. 仓库也可以托管在 gitlab 、gitee 、gerrit 等平台，可以增加一个选择的选项
> > > 4. 有的模板可能不止预设的几个涉及地址的字段，是否考虑改用其他方式，比如正则来匹配修改
> > > 5. LICENSE 同 4 ... 每个 LICENSE 可能不一样
> > > 
> > > 以上愚见，可以酌情考虑修改
> > 
> > 
> > 第一点不是很明白
> 
> 可以参考 Github REST API [get a repository](https://docs.github.com/en/rest/repos/repos#get-a-repository) ，一个仓库可以属于个人也可以属于组织，就是对应关系上，写成 owner 会更准确...

`src/index.ts` 里第 10 行，questions 的第一个问题，要改成 owner 更合适

**Comment by alexzhang1030** [comment]
> update log

1. done. https://github.com/alexzhang1030/pim/commit/9ac005a17de1ef49a77eff455590b0d68f61287c
2. todo
3. todo
4. todo
5. todo

**Comment by alexzhang1030** [comment]
@LoTwT 第四点有没有详细的说明，我不是太明白

**Comment by LoTwT** [comment]
> @LoTwT 第四点有没有详细的说明，我不是太明白

https://github.com/alexzhang1030/pim/blob/8a2897de90d49f4272121c712f1229c023fe258a/src/index.ts#L51 ，预设字段不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式

**Comment by alexzhang1030** [comment]
> > @LoTwT 第四点有没有详细的说明，我不是太明白
> 
> `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式

那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...

感觉有点怪怪的

**Comment by LoTwT** [comment]
> > > @LoTwT 第四点有没有详细的说明，我不是太明白
> > 
> > 
> > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> 
> 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> 
> 感觉有点怪怪的

`protocal://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..

**Comment by alexzhang1030** [comment]
> > > > @LoTwT 第四点有没有详细的说明，我不是太明白
> > > 
> > > 
> > > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> > 
> > 
> > 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> > 感觉有点怪怪的
> 
> `protocol://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..

所以用户如果使用的话，还需要提供一套需要让我解析的正则字段，emm 感觉食用起来并不方便

**Comment by LoTwT** [comment]
> > > > > @LoTwT 第四点有没有详细的说明，我不是太明白
> > > > 
> > > > 
> > > > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> > > 
> > > 
> > > 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> > > 感觉有点怪怪的
> > 
> > 
> > `protocol://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..
> 
> 所以用户如果使用的话，还需要提供一套需要让我解析的正则字段，emm 感觉食用起来并不方便

判定，设计如此！不用修复！

**Comment by alexzhang1030** [comment]
> > > > > > @LoTwT 第四点有没有详细的说明，我不是太明白
> 
> > > > > 
> 
> > > > > 
> 
> > > > > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> 
> > > > 
> 
> > > > 
> 
> > > > 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> 
> > > > 感觉有点怪怪的
> 
> > > 
> 
> > > 
> 
> > > `protocol://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..
> 
> > 
> 
> > 所以用户如果使用的话，还需要提供一套需要让我解析的正则字段，emm 感觉食用起来并不方便
> 
> 
> 
> 判定，设计如此！不用修复！

别呀，我只是不太明白用户如何使用

**Comment by LoTwT** [comment]
> > > > > > > @LoTwT 第四点有没有详细的说明，我不是太明白
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> > 
> > 
> > > > > 感觉有点怪怪的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > `protocol://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..
> > 
> > 
> > > 
> > 
> > 
> > > 所以用户如果使用的话，还需要提供一套需要让我解析的正则字段，emm 感觉食用起来并不方便
> > 
> > 
> > 判定，设计如此！不用修复！
> 
> 别呀，我只是不太明白用户如何使用

用户就正常输入鸭，只不过把预设字段改为正则匹配？把匹配的字段的值全部替换掉。。。

**Comment by alexzhang1030** [comment]
> > > > > > > > @LoTwT 第四点有没有详细的说明，我不是太明白
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> > > 
> > > 
> > > > > > 感觉有点怪怪的
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > `protocol://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 所以用户如果使用的话，还需要提供一套需要让我解析的正则字段，emm 感觉食用起来并不方便
> > > 
> > > 
> > > 判定，设计如此！不用修复！
> > 
> > 
> > 别呀，我只是不太明白用户如何使用
> 
> 用户就正常输入鸭，只不过把预设字段改为正则匹配？把匹配的字段的值全部替换掉。。。

不如成为 `pim` 的贡献者吧 😂

**Comment by LoTwT** [comment]
> > > > > > > > > @LoTwT 第四点有没有详细的说明，我不是太明白
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > `src/index.ts` 51 行的方法内，返回了预设字段，不利于扩展，需要一个通用的匹配字段，或者匹配结果的修改方式
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > > 那我匹配的话，是根据什么来匹配呢 🤔，用户给的？假设用户给的话，是不是需要给很多字段...
> > > > 
> > > > 
> > > > > > > 感觉有点怪怪的
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > `protocol://host:port/owner/repo(*)` 我也不知道我在写什么... 目前修改主要还是基于已有的模板，好像暂时也没碰见更多的字段需要修改了..
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 所以用户如果使用的话，还需要提供一套需要让我解析的正则字段，emm 感觉食用起来并不方便
> > > > 
> > > > 
> > > > 判定，设计如此！不用修复！
> > > 
> > > 
> > > 别呀，我只是不太明白用户如何使用
> > 
> > 
> > 用户就正常输入鸭，只不过把预设字段改为正则匹配？把匹配的字段的值全部替换掉。。。
> 
> 不如成为 `pim` 的贡献者吧 😂

😂明天试试
